# Set auto-connection minimum preferred interval to 7.5ms
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# Set peripheral-to-central connection interval to 11.25ms
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# Set latency to 0, meaning the peripheral will not skip any connection events and remain actively listening. This solves the issue where the peripheral cannot be woken by the central due to deep sleep, slightly increasing peripheral power consumption.
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Connection timeout threshold set to 4000ms; the connection will disconnect if there is no communication within this period.
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

# Enable rotary encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_EXT_POWER=y

# Increase keyboard debouncing
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable keyboard RGB features
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# Settings in this file apply to both sides of a split keyboard. Use side-specific .conf files when left and right halves require different feature configurations.

# Bluetooth enhancement
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Key remapping
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
